---

services:
  verba:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      #See .env.example or the Verba docs for more information about environmental variables
      
      # Audio transcription service - for multimodal only - otherwise comment out
      - ASSEMBLYAI_API_KEY = $ASSEMBLYAI_API_KEY

      # Vector database - API key needed only for cloud deployments 
      - WEAVIATE_URL_VERBA = $WEAVIATE_URL_VERBA
      - WEAVIATE_API_KEY_VERBA = $WEAVIATE_API_KEY_VERBA

      # Using OpenAI for embeddings and generation - for dev purposes only
      - OPENAI_API_KEY = $OPENAI_API_KEY

    healthcheck:
      test: wget --no-verbose --tries=3 --spider http://localhost:8000 || exit 1
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s